### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by guilhermearaujo** [blazsolar/android-collapse-calendar-view#3]
I was wondering if there is any way to force the calendar to use a specific locale, rather than the system's current locale. Is it possible?

Also, I noticed that when the calendar is collapsed to the week view, the header always says "week #". Can this header be localized too? Can we alternatively display the month of the selected date instead of the week number?

**Comment by blazsolar** [comment]
There is no easy way to do this at the moment. I will try to add some sort of formatter functionality.
